{{ if .Values.env }}
{{- if .Values.env.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}-secrets
type: Opaque
data:
{{- range .Files.Lines "secrets.env" }}
  {{- if . }}
  {{- $parts := regexSplit "=" . 2 }}
  {{ index $parts 0  }}: {{ index $parts 1 | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{ end  }}